[package]
name = "other_rustcrawl"
version = "0.1.0"
authors = ["a.bozzanoschwedhel"]

[dependencies]
hyper = "0.12.9"
tokio-core = "0.1.17"
futures = "0.1.23"
regex = "1.0.4"
url = "1.7.1"
serde = "1.0.76"
serde_json = "1.0.26"
serde_derive = "1.0.76"
ctrlc = "3.1.1"
hyper-tls = "0.3.1"